# -*- coding: utf-8 -*-
"""Combat-Online-Plagiarism-with-AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDoMWjWA7OwOQ4aE-l3CQBQqNUWzXIlZ
"""

from difflib import SequenceMatcher

with open("/content/fatma.txt") as file1, open("/content/john.txt") as file2, open("/content/juma.txt") as file3:
  file1data=file1.read()
  file2data=file2.read()
  file3data=file3.read()

similarity=SequenceMatcher(None,file1data,file2data).ratio()
similarity1=SequenceMatcher(None,file1data,file3data).ratio()
similarity2=SequenceMatcher(None,file2data,file3data).ratio()
print("'fatma.txt'","'join.txt'",similarity*100)
print("'fatma.txt'","'juma.txt'",similarity1*100)
print("'john.txt'","'juma.txt'",similarity*100)